export const emptyTask = {
  title: '',
  content: '',
  status: '',
  priority: '',
  start_time: '',
  end_time: '',
}

export const PROJECT_PAGE = {
  OPEN_FORM_MODAL: 'PROJECT_PAGE.OPEN_FORM_MODAL',
  UPDATE_TASK_FORM_DATA: 'PROJECT_PAGE.UPDATE_TASK_FORM_DATA',
  ADD_FORM_ERRORS: 'PROJECT_PAGE.ADD_FORM_ERRORS',
  CLEAR_FORM_FIELD_ERRORS: 'PROJECT_PAGE.CLEAR_FORM_FIELD_ERRORS',
  FETCH_TASKS: {
    REQUEST: 'PROJECT_PAGE.FETCH_TASKS.REQUEST',
    SUCCEED: 'PROJECT_PAGE.FETCH_TASKS.SUCCEED',
  },
  UPDATE_TASK: {
    REQUEST: 'PROJECT_PAGE.UPDATE_TASK.REQUEST',
    SUCCEED: 'PROJECT_PAGE.UPDATE_TASK.SUCCEED',
  },
}
