export const emptyTask = {
  title: '',
  content: '',
  status: '',
  priority: '',
  start_time: '',
  end_time: '',
}

export const FORM_TYPE = {
  CREATE: 'CREATE',
  UPDATE: 'UPDATE',
}

export const PROJECT_PAGE = {
  OPEN_FORM_MODAL: 'PROJECT_PAGE.OPEN_FORM_MODAL',
  SET_FORM_MODAL_IS_LOADING: 'PROJECT_PAGE.SET_FORM_MODAL_IS_LOADING',
  UPDATE_TASK_FORM_DATA: 'PROJECT_PAGE.UPDATE_TASK_FORM_DATA',
  ADD_FORM_ERRORS: 'PROJECT_PAGE.ADD_FORM_ERRORS',
  CLEAR_FORM_FIELD_ERRORS: 'PROJECT_PAGE.CLEAR_FORM_FIELD_ERRORS',
  FETCH_TASKS: {
    REQUEST: 'PROJECT_PAGE.FETCH_TASKS.REQUEST',
    SUCCEED: 'PROJECT_PAGE.FETCH_TASKS.SUCCEED',
  },
  CREATE_TASK: {
    REQUEST: 'PROJECT_PAGE.CREATE_TASK.REQUEST',
    SUCCEED: 'PROJECT_PAGE.CREATE_TASK.SUCCEED',
  },
  UPDATE_TASK: {
    REQUEST: 'PROJECT_PAGE.UPDATE_TASK.REQUEST',
    SUCCEED: 'PROJECT_PAGE.UPDATE_TASK.SUCCEED',
  },
}
