default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  port: 3306
  username: <%= Rails.application.credentials.dig(Rails.env.downcase.to_sym, :db, :username) %>
  password: <%= Rails.application.credentials.dig(Rails.env.downcase.to_sym, :db, :password) %>
  host: <%= Rails.application.credentials.dig(Rails.env.downcase.to_sym, :db, :host) %>

development:
  <<: *default
  database: astro_camp_traning_development

test:
  <<: *default
  database: astro_camp_traning_test

production:
  url: <%= ENV['CLEARDB_DATABASE_URL'] %>
