default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  port: 3306
  database: <%= "astro_camp_traning_#{Rails.env.downcase}" %>
  username: <%= Rails.application.credentials.dig(Rails.env.downcase.to_sym, :db, :username) %>
  password: <%= Rails.application.credentials.dig(Rails.env.downcase.to_sym, :db, :password) %>
  host: <%= Rails.application.credentials.dig(Rails.env.downcase.to_sym, :db, :host) %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
